name: build the docker image and deploy on aws

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v6

      - name: build docker image from dockerfile
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/qna-chatbot:latest .

      - name: login to docker hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: push docker image to docker hub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/qna-chatbot:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: deploy to aws
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/qna-chatbot:latest
            docker stop qna-chatbot || true 
            docker rm qna-chatbot || true 
            docker run -d --restart unless-stopped -p 127.0.0.1:8080:8000 \
            -e OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} \
            --name qna-chatbot ${{ secrets.DOCKER_USERNAME }}/qna-chatbot:latest